Add sample app that shows MVVM with View Models
androiddevnotes/awesome-android-kotlin-apps pull request #45
Opened 2020-10-10 05:23 UTC by adityakamath16

This app is simple yet it covers all features like:-
MVVM architecture, Dagger, Retrofit, Kotlin Coroutines, RXJava2, View Models, Data Binding

2020-10-10 15:47 UTC, androiddevnotes requested changes
Thank you for the Pull Request!

Proper formatting, please. 

Pay attention to the spacing between comma and text in Tech Stack.

View Models should be written as ViewModel.

Please join the Discord server where we discuss open-source, android dev, and content creation. Invite link - https://discord.gg/vBnEhuC

2020-10-10 16:05 UTC, adityakamath16 commented
Requested changes have been done, please review it :-)
Thank you.

2020-10-11 11:04 UTC, androiddevnotes approved these changes

2020-10-11 11:04 UTC, merged

2020-10-11 11:04 UTC, androiddevnotes commented
Thank You!